# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  mediatrapp:
    image: mediatrapp
    build:
      context: .
      dockerfile: Dockerfile-webapi
    ports:
      - 8000:80